### ISSUE TITLE
Other Models?

### ISSUE THREAD

**Issue by kjfjsd99** [RuneSkovrupHansen/openvino#1]
Hi, 
thanks for your turtorial. 
I just want to ask that is it possible to run with the models like yolo-v4-tf by using your code? 
I have ever tried but it didn't work.
Thank you

**Comment by RuneSkovrupHansen** [comment]
Hey @kjfjsd99. The yolo-v4-tf model definitely works with OpenVino, it is a model that is included as part of their model zoo. [Link to model zoo repo](https://github.com/openvinotoolkit/open_model_zoo), [Link to yolo-v4-tf model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/yolo-v4-tf/README.md).

I spent a bit of time playing around with the model, and I was able to get it to make predictions, but I was unable to properly interpret the output format.

What I would do, if you want to get it to work, is to get the demo for the model running in the model zoo, you can find it [here](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo/python/README.md), and afterwards take a look at how the demo is making predictions with that model, specifically check out the file  [object_detection_demo.py](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo/python/object_detection_demo.py)
